package fr.cornysneeze.aircraftmod.blocks;

import net.minecraftforge.common.ForgeConfigSpec;

public class CoalgenConfig {

    public static ForgeConfigSpec.IntValue COALGEN_CAPACITY;
    public static ForgeConfigSpec.IntValue COALGEN_GENERATE;
    public static ForgeConfigSpec.IntValue COALGEN_SEND;


    public static void registerServerConfig(ForgeConfigSpec.Builder SERVER_BUILDER) {
        SERVER_BUILDER.comment("Settings for the coal generator").push("coalgen");

        COALGEN_CAPACITY = SERVER_BUILDER
                .comment("How much energy fits into the coal generator")
                .defineInRange("capacity", 10000, 1, Integer.MAX_VALUE);
        COALGEN_GENERATE = SERVER_BUILDER
                .comment("How much energy is generated by the coal generator")
                .defineInRange("generate", 1, 1, Integer.MAX_VALUE);
        COALGEN_SEND = SERVER_BUILDER
                .comment("How much energy the coal generator will send out to adjacent blocks every tick")
                .defineInRange("send", 200, 1, Integer.MAX_VALUE);


        SERVER_BUILDER.pop();
    }

    public static void registerClientConfig(ForgeConfigSpec.Builder CLIENT_BUILDER) {
        CLIENT_BUILDER.comment("Client settings for the power generator").push("coalgen");


        CLIENT_BUILDER.pop();
    }
}
